TRUTH = (
    "Bạn đã từng mê ai đó chưa?"
     "Bạn đã bao giờ đi ngang qua bố mẹ mình làm 'chuyện ấy' chưa?",
     "Ai là người cuối cùng bạn thích nhất? Tại sao?",
     "Bạn đã bao giờ bị đình chỉ học chưa?",
     "Nếu bạn phải chọn giữa khỏa thân hoặc để suy nghĩ của bạn xuất hiện trong một bong bóng suy nghĩ trên đầu cho tất cả mọi người đọc, bạn sẽ chọn cái nào?",
     "Một thứ mà bạn sợ mất là gì?"
     "Bạn có thích ai đó ngay bây giờ không?",
     "Một điều về người bạn thân nhất của bạn khiến bạn ghen tị?",
     "Bạn định lừa dối bạn trai của bạn để lấy một anh chàng giàu có?",
     "Bước ngoặt lớn nhất của bạn là gì?",
     "Lần cuối cùng bạn nói dối bố mẹ là khi nào và tại sao?",
     "Mô tả người bạn đời lý tưởng của bạn.",
     "Điều đáng sợ nhất mà bạn từng làm là gì?"
     "Bạn đã bao giờ ngoáy mũi và ăn nó chưa?",
     "Lần cuối cùng bạn nói dối bố mẹ là khi nào và tại sao?",
     "Bạn đã bao giờ nói dối về tuổi của mình để tham gia một cuộc thi chưa?",
     “Bạn đã bao giờ bị bắt gặp đang kiểm tra ai đó chưa?"
)

DARE = (
    "Hiển thị những bức ảnh đáng xấu hổ nhất trên điện thoại của bạn "
     "Hiển thị năm người cuối cùng bạn đã nhắn tin và tin nhắn của họ là gì",
     "Cho phép cả nhóm gửi tin nhắn trực tiếp cho ai đó từ tài khoản Instagram của bạn",
     "Ăn tỏi sống",
     "Thực hiện 100 lần squat",
     "Giữ ba viên đá trong miệng của bạn cho đến khi nó tan chảy",
     "Nói điều gì đó bẩn thỉu với người bên trái của bạn. Bạn có bạn!",
     "Hãy mát-xa chân cho người ở bên phải bạn",
     "Cho 10 chất lỏng có sẵn khác nhau vào cốc và uống",
     "* Hãy nói từ đầu tiên xuất hiện trong đầu bạn",
     "Hãy múa đùi cho người bạn chọn",
     "Cởi bốn mảnh quần áo",
     "Thích 15 bài đăng đầu tiên trên nguồn cấp tin tức Facebook của bạn",
     "Ăn một thìa mù tạt",
     "Nhắm mắt cho đến khi bạn lại ra đi",
     "Gửi sext cho người cuối cùng trong danh bạ của bạn",
     "Khoe khuôn mặt cực khoái của bạn",
     "Ăn chuối một cách quyến rũ",
     "Làm trống ví / ví của bạn và cho mọi người thấy có gì trong đó",
     "Hãy cố gắng thu thập thông tin sexy nhất của bạn",
     "Giả vờ là người ở bên phải bạn trong 10 phút",
     "Ăn vặt không cần dùng tay",
     "Hãy nói hai điều trung thực về mọi người trong nhóm",
     "Twerk một chút",
     "Cố gắng làm cho cả nhóm cười càng nhanh càng tốt",
     "Cố gắng đưa cả nắm tay vào miệng",
     "Hãy kể cho mọi người nghe một câu chuyện đáng xấu hổ về bản thân bạn",
     "Cố gắng liếm khuỷu tay của bạn",
     "Đăng ảnh tự chụp lâu đời nhất trên điện thoại của bạn trên Câu chuyện Instagram",
     "Hãy kể cho tôi nghe câu chuyện buồn nhất mà bạn biết",
     "Hú lên như một con sói trong hai phút",
     "Nhảy mà không có nhạc trong hai phút",
     "Múa cột với những chiếc cột tưởng tượng",
     "Hãy để người khác cù bạn và cố gắng không cười"
     "Đưa đồ ăn nhẹ vào miệng cùng lúc nhiều nhất có thể",
     "Gửi ảnh tự chụp mới nhất của bạn.",
     "Gửi ảnh tự sướng xấu xí nhất của bạn.",
     "Gửi ảnh chụp màn hình lịch sử tìm kiếm trên facebook của bạn",
     "Gửi ảnh chụp màn hình phòng trưng bày của bạn.",
     "Gửi ảnh chụp màn hình hộp thư đến Messenger của bạn",
     "Hãy nói điều gì đó rất thân mật.",
     "Gửi ảnh chụp màn hình hộp thư đến twitter của bạn",
     "Gửi ảnh chụp màn hình chính của bạn.",
     "Gửi bản cover bài hát yêu thích của bạn.",
     "Làm một trò đùa có lời về một người nào đó và gửi bằng chứng.",
     "Thừa nhận người yêu hiện tại của bạn. ❤️",
     "Hãy cho tôi biết tình yêu đích thực của bạn là ai.",
     "Gửi ảnh chụp màn hình phòng trưng bày của bạn.",
     "Đặt ảnh của người ấy làm ảnh dp của bạn.",
     "Đề nghị tôi táo bạo hơn.",
)
